Controllers/FriendsController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using WaterCool.Models;
using WaterCool.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.SignalR;

namespace WaterCool.Controllers
{
    public class FriendsController : Controller
    {
        [Authorize]
        public IActionResult List()
        {
            int u_Id = Int32.Parse(HttpContext.User.FindFirst(ClaimTypes.Sid).Value) ;
            List<Friendship> newList = fakerDB.Friends.Join(fakerDB.Infos, Friendship => Friendship.friend_id, Info => Info.userId , (Friendship, info) => new Friendship{ user_id = Friendship.user_id, friend_id = Friendship.friend_id, fri_name = Friendship.fri_name, photo = info.photoAddress }).Cast<Friendship>().ToList();
            List<Friendship> FriendsList = newList.FindAll(x => x.user_id == u_Id);
            return View(FriendsList);
            
        }
        [Authorize]
        [HttpPost]
        public IActionResult getMessage(string from, int num)
        {
            int come = Int32.Parse(from);
            int go = Int32.Parse(HttpContext.User.FindFirst(ClaimTypes.Sid).Value);
            List<MessageModel> resultA = fakerDB.Messages.FindAll( x => x.FromId == come && x.ToId == go);
            List<MessageModel> resultB = fakerDB.Messages.FindAll(x => x.FromId == go && x.ToId == come);
            var  resultC =(resultA.Union(resultB)).OrderBy(x => x.date);
            int count = resultC.Count()-num;
            if(count < 0)
            {
                count = 0;
            }
            var result = resultC.Skip(count).Take(num);
            return new ObjectResult(result);
        }
        [Authorize]
        [HttpPost]
        public IActionResult MakeFriend( int id )
        {
            int uid =Int32.Parse(HttpContext.User.FindFirst(ClaimTypes.Sid).Value);
            int fid = id;
            Friendship relation = fakerDB.Friends.FirstOrDefault(x => x.user_id == uid && x.friend_id == fid);
            if(relation != null)
            {
                return Json(new { status="error",message="已是好友關係"});
            }
            else
            {
                fakerDB.Friends.Add( new Friendship{ user_id = uid, friend_id = fid, fri_name = fakerDB.Users.FirstOrDefault(x => x.id == fid).Username });
                fakerDB.Friends.Add( new Friendship{ user_id = fid, friend_id = uid, fri_name = fakerDB.Users.FirstOrDefault(x => x.id == uid).Username });
                return Json(new { status="success",message="你們已成為好友"});
            }
            
        }
        [Authorize]
        [HttpPost]
        public IActionResult SearchFriends( string Username)
        {
            List<User> newList = fakerDB.Users.Join(fakerDB.Infos, User => User.id, Info => Info.userId , (User, info) => new User{ id = User.id, Username = User.Username, photo = info.photoAddress }).Cast<User>().ToList();
            List<User> UserList = newList.FindAll(x => x.Username == Username);
            if(UserList.Count <=0)
            {
                ViewBag.msg = "查無此人!";
                return View();
            }
            return View(UserList);
        }

    }
}

Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WaterCool.Models;
using WaterCool.Data;
using System.Security.Claims;

namespace WaterCool.Controllers
{
    public class PostController : Controller
    {
        [Authorize()]
        public IActionResult Post()
        {
            return View();
        }
        [Authorize()]
        [HttpPost]
        public IActionResult Post(  string content )
        {
            PostsModel post = new PostsModel()
            {
                postId = fakerDB.Posts.Count > 0 ? fakerDB.Posts.Max(x => x.postId)+1 : 0,
                userId = Int32.Parse(HttpContext.User.FindFirst(ClaimTypes.Sid).Value),
                context = content,
                update = DateTime.Now.ToString()
            };
            fakerDB.Posts.Add(post);
            return new JsonResult(post);
        }
        [Authorize()]
        [HttpPost]
        public IActionResult GetPost(int count)
        {
            int idx = Int32.Parse( HttpContext.User.FindFirst(ClaimTypes.Sid).Value );
            //int idx = 1;
            List<Friendship> Friends = fakerDB.Friends.FindAll(x => x.friend_id == idx);
            List<PostsModel> posts = fakerDB.Posts.FindAll(x => x.userId == idx);
            foreach( Friendship F in Friends)
            {
                List<PostsModel> tmp =  fakerDB.Posts.FindAll(x => x.userId == F.user_id);
                foreach( PostsModel p in tmp)
                {
                    posts.Add(p);
                }
            }
            if(posts.Count > 0)
            {
                var result = fakerDB.Users.Join(posts,  User => User.id,PostsModel => PostsModel.userId,  ( User, PostsModel) => new { postId = PostsModel.postId ,userId = User.id, Author = User.Username, context = PostsModel.context, update = PostsModel.update, commend = fakerDB.commends.FindAll(x => x.postId == PostsModel.postId) } );
                return new ObjectResult(result.OrderByDescending(x => x.update).Take(count));
            }

            return new ObjectResult(new { Status = 0 });
        }
        [Authorize]
        [HttpPost]
        public IActionResult PostCommend(int postID, string context)
        {
            CommendModel comm = new CommendModel{ postId = postID, userID =Int32.Parse(HttpContext.User.FindFirst(ClaimTypes.Sid).Value),username = HttpContext.User.FindFirst(ClaimTypes.Name).Value,  commend = context };
            fakerDB.commends.Add(comm);
            return new ObjectResult(comm);
        }
    }
}

Views/Shared/_Layout.cshtml
@using System.Security.Claims 
<!DOCTYPE html>
<html style="height:100%;">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WaterCool</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.css" />
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body style="height:100%;">
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <span class="navbar-brand">WaterCool</span>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav ">
                    <li>
                        <a asp-area="" asp-controller="Post" asp-action="Post">動態消息 </a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Friends" asp-action="List">好友 </a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="Self">Info </a>
                    </li>
                    @if(User.Identity.IsAuthenticated){
                        <li>
                            <form style="padding-top:10px;" asp-controller="Friends" asp-action="SearchFriends"><input style="width:250px;" type="text" id = "Username" name ="Username" placeholder="測試搜尋功能請輸入'custom'"><button type="submit">搜尋</button></form>
                        </li>
                    }
                </ul>
                @if (User.Identity.IsAuthenticated){ 
                        <form asp-area="" asp-controller="Auth" asp-action="Logout" method="post" id="logoutForm" class="navbar-right">
                            <ul class="nav navbar-nav navbar-right">
                                <li>
                                    Hello<label type ="label" id ="Username" >@User.Identity.Name</label> 
                                </li>
                                <li>
                                    <button type="submit" class="btn btn-link navbar-btn navbar-link">Log out</button>
                                </li>
                            </ul>
                        </form>
                }
            </div>
        </div>
    </nav>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    @RenderSection("Scripts", required: false)
    
    <div class="container body-content" style="height:85%;">
        @RenderBody()
        
    </div>
        <footer>
            <p>&copy; 2017 - WaterCool</p>
        </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.js"></script>
    <script src="~/js/signalr-client.min.js"></script>
    
    <environment include="Development">
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/js/signalr-client.min.js"></script>
    </environment>

</body>
</html>